export const PROTOCOLS = [
  {
    key: "pace", label: "VELOCIDAD", abbr: "PAC", color: "#00d4ff", icon: "⚡",
    description: "Mide la velocidad máxima de sprint y aceleración explosiva del jugador en cancha.",
    equipment: [
      "Conos de señalización", "Cronómetro o app de timing",
      "Cinta métrica (30 m)", "Pista plana de césped o sintético",
    ],
    tests: [
      {
        name: "Sprint 30 metros", objective: "Medir velocidad máxima de carrera",
        setup: "Coloca conos a 0 m y 30 m en línea recta. El jugador parte desde posición estática con un pie adelantado.",
        execution: "El evaluador da la señal (silbato). El jugador acelera a máxima velocidad hasta la línea. Se cronometra desde la señal hasta cruzar la línea.",
        attempts: 2, best: "Se toma el mejor de 2 intentos (3 min descanso entre ellos).",
        unit: "segundos",
        scoring: {
          sub10:  [{range:"< 5.5",    pts:"90–99", label:"Élite"},         {range:"5.5–6.0",  pts:"74–89", label:"Muy rápido"},  {range:"6.1–6.8",  pts:"54–73", label:"Bueno"},   {range:"6.9–7.5",  pts:"32–53", label:"Promedio"},  {range:"> 7.5",   pts:"10–31", label:"Por mejorar"}],
          sub12:  [{range:"< 5.0",    pts:"90–99", label:"Élite"},         {range:"5.0–5.5",  pts:"74–89", label:"Muy rápido"},  {range:"5.6–6.2",  pts:"54–73", label:"Bueno"},   {range:"6.3–7.0",  pts:"32–53", label:"Promedio"},  {range:"> 7.0",   pts:"10–31", label:"Por mejorar"}],
          sub14:  [{range:"< 4.5",    pts:"90–99", label:"Élite"},         {range:"4.5–4.9",  pts:"74–89", label:"Muy rápido"},  {range:"5.0–5.5",  pts:"54–73", label:"Bueno"},   {range:"5.6–6.2",  pts:"32–53", label:"Promedio"},  {range:"> 6.2",   pts:"10–31", label:"Por mejorar"}],
          sub16:  [{range:"< 4.2",    pts:"90–99", label:"Élite"},         {range:"4.2–4.6",  pts:"74–89", label:"Muy rápido"},  {range:"4.7–5.1",  pts:"54–73", label:"Bueno"},   {range:"5.2–5.8",  pts:"32–53", label:"Promedio"},  {range:"> 5.8",   pts:"10–31", label:"Por mejorar"}],
          sub18:  [{range:"< 4.0",    pts:"90–99", label:"Élite"},         {range:"4.0–4.4",  pts:"74–89", label:"Muy rápido"},  {range:"4.5–4.9",  pts:"54–73", label:"Bueno"},   {range:"5.0–5.5",  pts:"32–53", label:"Promedio"},  {range:"> 5.5",   pts:"10–31", label:"Por mejorar"}],
          sub21:  [{range:"< 3.9",    pts:"90–99", label:"Élite"},         {range:"3.9–4.2",  pts:"74–89", label:"Muy rápido"},  {range:"4.3–4.7",  pts:"54–73", label:"Bueno"},   {range:"4.8–5.3",  pts:"32–53", label:"Promedio"},  {range:"> 5.3",   pts:"10–31", label:"Por mejorar"}],
          senior: [{range:"< 3.8",    pts:"92–99", label:"Élite mundial"}, {range:"3.8–4.1",  pts:"78–91", label:"Muy rápido"},  {range:"4.2–4.5",  pts:"58–77", label:"Rápido"},  {range:"4.6–4.9",  pts:"38–57", label:"Promedio"},  {range:"> 4.9",   pts:"10–37", label:"Lento"}],
        },
      },
      {
        name: "Aceleración 10 metros", objective: "Medir capacidad de arranque explosivo",
        setup: "Conos a 0 m y 10 m. Parte desde posición estática con un pie adelantado.",
        execution: "Mismo protocolo que 30 m. Se cronometra solo la llegada a los 10 m.",
        attempts: 2, best: "Se promedia con sprint 30 m según fórmula.",
        unit: "segundos",
        scoring: {
          sub10:  [{range:"< 2.2",    pts:"90–99", label:"Explosivo élite"}, {range:"2.2–2.5",   pts:"72–89", label:"Muy explosivo"}, {range:"2.6–2.9",   pts:"50–71", label:"Bueno"},   {range:"3.0–3.4",   pts:"28–49", label:"Promedio"}, {range:"> 3.4",   pts:"10–27", label:"Por mejorar"}],
          sub12:  [{range:"< 2.0",    pts:"90–99", label:"Explosivo élite"}, {range:"2.0–2.3",   pts:"72–89", label:"Muy explosivo"}, {range:"2.4–2.7",   pts:"50–71", label:"Bueno"},   {range:"2.8–3.2",   pts:"28–49", label:"Promedio"}, {range:"> 3.2",   pts:"10–27", label:"Por mejorar"}],
          sub14:  [{range:"< 1.9",    pts:"90–99", label:"Explosivo élite"}, {range:"1.9–2.1",   pts:"72–89", label:"Muy explosivo"}, {range:"2.2–2.5",   pts:"50–71", label:"Bueno"},   {range:"2.6–2.9",   pts:"28–49", label:"Promedio"}, {range:"> 2.9",   pts:"10–27", label:"Por mejorar"}],
          sub16:  [{range:"< 1.8",    pts:"90–99", label:"Explosivo élite"}, {range:"1.8–2.0",   pts:"72–89", label:"Muy explosivo"}, {range:"2.1–2.3",   pts:"50–71", label:"Bueno"},   {range:"2.4–2.7",   pts:"28–49", label:"Promedio"}, {range:"> 2.7",   pts:"10–27", label:"Por mejorar"}],
          sub18:  [{range:"< 1.75",   pts:"90–99", label:"Explosivo élite"}, {range:"1.75–1.95", pts:"72–89", label:"Muy explosivo"}, {range:"1.96–2.15", pts:"50–71", label:"Bueno"},   {range:"2.16–2.45", pts:"28–49", label:"Promedio"}, {range:"> 2.45",  pts:"10–27", label:"Por mejorar"}],
          sub21:  [{range:"< 1.70",   pts:"90–99", label:"Explosivo élite"}, {range:"1.70–1.90", pts:"72–89", label:"Muy explosivo"}, {range:"1.91–2.10", pts:"50–71", label:"Bueno"},   {range:"2.11–2.40", pts:"28–49", label:"Promedio"}, {range:"> 2.40",  pts:"10–27", label:"Por mejorar"}],
          senior: [{range:"< 1.65",   pts:"92–99", label:"Explosivo élite"}, {range:"1.65–1.80", pts:"76–91", label:"Muy explosivo"}, {range:"1.81–1.95", pts:"56–75", label:"Bueno"},   {range:"1.96–2.10", pts:"34–55", label:"Promedio"}, {range:"> 2.10",  pts:"10–33", label:"Por mejorar"}],
        },
      },
    ],
    formula: "PAC = (Sprint 30m × 0.60) + (Aceleración 10m × 0.40)",
  },
  {
    key: "shooting", label: "DISPARO", abbr: "SHO", color: "#ff6b6b", icon: "🎯",
    description: "Evalúa la potencia, precisión y técnica de remate al arco desde distintas situaciones.",
    equipment: [
      "Balones de fútbol (mínimo 5)", "Arco reglamentario",
      "Cinta adhesiva para zonas", "Cinta métrica", "Velocímetro de balón (opcional)",
    ],
    tests: [
      {
        name: "Precisión de disparo (10 remates)", objective: "Medir acierto al arco dividido en zonas ponderadas",
        setup: "Divide el arco en 6 zonas: esquinas altas (2 pts c/u), esquinas bajas (2 pts), centros (1 pt). Distancia varía por categoría.",
        execution: "El jugador ejecuta 10 disparos al arco estático sin portero. Esquinas valen 2 pts, centros 1 pt. Máximo 20 pts.",
        attempts: 10, best: "Suma total de puntos por zona acertada.",
        unit: "puntos (máx 20)",
        scoring: {
          sub10:  [{range:"15–20 pts", pts:"88–99", label:"Francotirador"}, {range:"11–14 pts", pts:"68–87", label:"Muy preciso"}, {range:"7–10 pts", pts:"46–67", label:"Preciso"}, {range:"3–6 pts", pts:"24–45", label:"Regular"}, {range:"0–2 pts", pts:"10–23", label:"Por mejorar"}],
          sub12:  [{range:"15–20 pts", pts:"88–99", label:"Francotirador"}, {range:"11–14 pts", pts:"68–87", label:"Muy preciso"}, {range:"7–10 pts", pts:"46–67", label:"Preciso"}, {range:"3–6 pts", pts:"24–45", label:"Regular"}, {range:"0–2 pts", pts:"10–23", label:"Por mejorar"}],
          sub14:  [{range:"16–20 pts", pts:"90–99", label:"Francotirador"}, {range:"12–15 pts", pts:"72–89", label:"Muy preciso"}, {range:"8–11 pts", pts:"52–71", label:"Preciso"}, {range:"4–7 pts", pts:"30–51", label:"Regular"}, {range:"0–3 pts", pts:"10–29", label:"Por mejorar"}],
          sub16:  [{range:"17–20 pts", pts:"90–99", label:"Francotirador"}, {range:"13–16 pts", pts:"72–89", label:"Muy preciso"}, {range:"9–12 pts", pts:"52–71", label:"Preciso"}, {range:"5–8 pts", pts:"30–51", label:"Regular"}, {range:"0–4 pts", pts:"10–29", label:"Por mejorar"}],
          sub18:  [{range:"17–20 pts", pts:"90–99", label:"Francotirador"}, {range:"13–16 pts", pts:"74–89", label:"Muy preciso"}, {range:"9–12 pts", pts:"54–73", label:"Preciso"}, {range:"5–8 pts", pts:"32–53", label:"Regular"}, {range:"0–4 pts", pts:"10–31", label:"Por mejorar"}],
          sub21:  [{range:"17–20 pts", pts:"90–99", label:"Francotirador"}, {range:"13–16 pts", pts:"74–89", label:"Muy preciso"}, {range:"9–12 pts", pts:"54–73", label:"Preciso"}, {range:"5–8 pts", pts:"32–53", label:"Regular"}, {range:"0–4 pts", pts:"10–31", label:"Por mejorar"}],
          senior: [{range:"17–20 pts", pts:"90–99", label:"Francotirador"}, {range:"13–16 pts", pts:"74–89", label:"Muy preciso"}, {range:"9–12 pts", pts:"54–73", label:"Preciso"}, {range:"5–8 pts", pts:"30–53", label:"Regular"}, {range:"0–4 pts", pts:"10–29", label:"Por mejorar"}],
        },
      },
      {
        name: "Potencia de disparo", objective: "Velocidad máxima del balón con pierna dominante",
        setup: "Balón estático. Distancia al arco varía por categoría. Velocímetro detrás del arco.",
        execution: "3 disparos máximos con pierna dominante. Se registra velocidad en km/h.",
        attempts: 3, best: "Se toma la velocidad máxima de los 3 intentos.",
        unit: "km/h",
        scoring: {
          sub10:  [{range:"> 45",   pts:"90–99", label:"Potente"},         {range:"35–45",  pts:"70–89", label:"Bueno"},          {range:"25–34",  pts:"48–69", label:"Normal"},   {range:"< 25",   pts:"10–47", label:"Básico"}],
          sub12:  [{range:"> 55",   pts:"90–99", label:"Cañonero"},        {range:"45–55",  pts:"70–89", label:"Potente"},         {range:"33–44",  pts:"48–69", label:"Bueno"},    {range:"< 33",   pts:"10–47", label:"Por mejorar"}],
          sub14:  [{range:"> 70",   pts:"90–99", label:"Cañonero"},        {range:"58–70",  pts:"70–89", label:"Potente"},         {range:"44–57",  pts:"48–69", label:"Bueno"},    {range:"< 44",   pts:"10–47", label:"Por mejorar"}],
          sub16:  [{range:"> 85",   pts:"90–99", label:"Cañonero"},        {range:"72–85",  pts:"70–89", label:"Potente"},         {range:"56–71",  pts:"48–69", label:"Bueno"},    {range:"< 56",   pts:"10–47", label:"Por mejorar"}],
          sub18:  [{range:"> 95",   pts:"90–99", label:"Cañonero"},        {range:"80–95",  pts:"70–89", label:"Potente"},         {range:"62–79",  pts:"48–69", label:"Bueno"},    {range:"< 62",   pts:"10–47", label:"Por mejorar"}],
          sub21:  [{range:"> 105",  pts:"90–99", label:"Cañonero élite"},  {range:"88–105", pts:"72–89", label:"Muy potente"},     {range:"68–87",  pts:"50–71", label:"Bueno"},    {range:"< 68",   pts:"10–49", label:"Por mejorar"}],
          senior: [{range:"> 110",  pts:"90–99", label:"Cañonero élite"},  {range:"90–110", pts:"72–89", label:"Muy potente"},     {range:"70–89",  pts:"50–71", label:"Bueno"},    {range:"< 70",   pts:"10–49", label:"Por mejorar"}],
        },
      },
    ],
    formula: "SHO = (Precisión × 0.55) + (Potencia × 0.30) + (Técnica observada × 0.15)",
  },
  {
    key: "passing", label: "PASE", abbr: "PAS", color: "#00ff88", icon: "🔁",
    description: "Evalúa la precisión, variedad y visión de juego en la distribución del balón.",
    equipment: [
      "Balones de fútbol (mínimo 6)", "5 conos en posiciones variables", "Cinta métrica",
    ],
    tests: [
      {
        name: "Precisión pase corto/medio (10 pases)", objective: "Porcentaje de pases completados a blancos en distintas distancias",
        setup: "5 conos a distancias variables por categoría en ángulos distintos. 2 pases por cono. Acierto = balón a menos de 1 m del cono.",
        execution: "El jugador ejecuta 10 pases alternando pies. Se registran los aciertos.",
        attempts: 10, best: "Total de pases precisos sobre 10.",
        unit: "aciertos / 10",
        scoring: {
          sub10:  [{range:"9–10",  pts:"90–99", label:"Perfecto"},  {range:"7–8",   pts:"70–89", label:"Muy preciso"}, {range:"5–6",  pts:"48–69", label:"Bueno"},    {range:"3–4",  pts:"26–47", label:"Regular"},  {range:"< 3",  pts:"10–25", label:"Por mejorar"}],
          sub12:  [{range:"9–10",  pts:"90–99", label:"Perfecto"},  {range:"7–8",   pts:"70–89", label:"Muy preciso"}, {range:"5–6",  pts:"48–69", label:"Bueno"},    {range:"3–4",  pts:"26–47", label:"Regular"},  {range:"< 3",  pts:"10–25", label:"Por mejorar"}],
          sub14:  [{range:"10/10", pts:"95–99", label:"Perfecto"},  {range:"8–9",   pts:"76–94", label:"Muy preciso"}, {range:"6–7",  pts:"54–75", label:"Bueno"},    {range:"4–5",  pts:"32–53", label:"Regular"},  {range:"< 4",  pts:"10–31", label:"Por mejorar"}],
          sub16:  [{range:"10/10", pts:"95–99", label:"Perfecto"},  {range:"8–9",   pts:"76–94", label:"Muy preciso"}, {range:"6–7",  pts:"54–75", label:"Bueno"},    {range:"4–5",  pts:"32–53", label:"Regular"},  {range:"< 4",  pts:"10–31", label:"Por mejorar"}],
          sub18:  [{range:"10/10", pts:"95–99", label:"Perfecto"},  {range:"8–9",   pts:"78–94", label:"Muy preciso"}, {range:"6–7",  pts:"56–77", label:"Bueno"},    {range:"4–5",  pts:"34–55", label:"Regular"},  {range:"< 4",  pts:"10–33", label:"Por mejorar"}],
          sub21:  [{range:"10/10", pts:"95–99", label:"Perfecto"},  {range:"8–9",   pts:"78–94", label:"Muy preciso"}, {range:"6–7",  pts:"58–77", label:"Bueno"},    {range:"4–5",  pts:"36–57", label:"Regular"},  {range:"< 4",  pts:"10–35", label:"Por mejorar"}],
          senior: [{range:"10/10", pts:"95–99", label:"Perfecto"},  {range:"8–9",   pts:"78–94", label:"Muy preciso"}, {range:"6–7",  pts:"58–77", label:"Bueno"},    {range:"4–5",  pts:"38–57", label:"Regular"},  {range:"< 4",  pts:"10–37", label:"Por mejorar"}],
        },
      },
      {
        name: "Pase largo (8 intentos)", objective: "Precisión en pases largos a zona circular de 3 m",
        setup: "Zona circular de 3 m a distancia variable por categoría. 5 con pierna dominante + 3 con pierna no dominante.",
        execution: "Se anota acierto si el balón cae dentro o toca la zona. Se registran por separado.",
        attempts: 8, best: "Total de aciertos ponderados sobre 8.",
        unit: "aciertos / 8",
        scoring: {
          sub10:  [{range:"6–8",  pts:"88–99", label:"Visión élite"}, {range:"4–5",  pts:"64–87", label:"Muy bueno"}, {range:"2–3",  pts:"38–63", label:"Bueno"},   {range:"0–1",  pts:"10–37", label:"Por mejorar"}],
          sub12:  [{range:"6–8",  pts:"88–99", label:"Visión élite"}, {range:"4–5",  pts:"64–87", label:"Muy bueno"}, {range:"2–3",  pts:"38–63", label:"Bueno"},   {range:"0–1",  pts:"10–37", label:"Por mejorar"}],
          sub14:  [{range:"7–8",  pts:"88–99", label:"Visión élite"}, {range:"5–6",  pts:"66–87", label:"Muy bueno"}, {range:"3–4",  pts:"42–65", label:"Bueno"},   {range:"1–2",  pts:"20–41", label:"Regular"},  {range:"0",    pts:"10–19", label:"Por mejorar"}],
          sub16:  [{range:"7–8",  pts:"88–99", label:"Visión élite"}, {range:"5–6",  pts:"68–87", label:"Muy bueno"}, {range:"3–4",  pts:"44–67", label:"Bueno"},   {range:"1–2",  pts:"22–43", label:"Regular"},  {range:"0",    pts:"10–21", label:"Por mejorar"}],
          sub18:  [{range:"7–8",  pts:"88–99", label:"Visión élite"}, {range:"5–6",  pts:"68–87", label:"Muy bueno"}, {range:"3–4",  pts:"46–67", label:"Bueno"},   {range:"1–2",  pts:"24–45", label:"Regular"},  {range:"0",    pts:"10–23", label:"Por mejorar"}],
          sub21:  [{range:"7–8",  pts:"88–99", label:"Visión élite"}, {range:"5–6",  pts:"68–87", label:"Muy bueno"}, {range:"3–4",  pts:"46–67", label:"Bueno"},   {range:"1–2",  pts:"24–45", label:"Regular"},  {range:"0",    pts:"10–23", label:"Por mejorar"}],
          senior: [{range:"7–8",  pts:"88–99", label:"Visión élite"}, {range:"5–6",  pts:"68–87", label:"Muy bueno"}, {range:"3–4",  pts:"46–67", label:"Bueno"},   {range:"1–2",  pts:"24–45", label:"Regular"},  {range:"0",    pts:"10–23", label:"Por mejorar"}],
        },
      },
    ],
    formula: "PAS = (Precisión corto/medio × 0.50) + (Pase largo × 0.35) + (Pierna no dominante × 0.15)",
  },
  {
    key: "dribbling", label: "REGATE", abbr: "DRI", color: "#ffd93d", icon: "🌀",
    description: "Mide el control del balón en movimiento, cambios de dirección y habilidad técnica individual.",
    equipment: [
      "Balones de fútbol", "8 conos de slalom separados 1.5 m",
      "Cronómetro", "Espacio mínimo 20 m",
    ],
    tests: [
      {
        name: "Slalom cronometrado (ida y vuelta)", objective: "Velocidad de conducción con regate entre conos",
        setup: "8 conos separados 1.5 m en línea recta (~12 m). Ida y vuelta en slalom. +0.5 seg por cono derribado.",
        execution: "Conducción en zigzag de ida y de vuelta sin perder el balón. Balón perdido = intento inválido.",
        attempts: 2, best: "Mejor tiempo válido de 2 intentos.",
        unit: "segundos",
        scoring: {
          sub10:  [{range:"< 10.0",   pts:"90–99", label:"Maestro"},         {range:"10.0–12.0", pts:"70–89", label:"Muy hábil"},  {range:"12.1–14.5", pts:"48–69", label:"Bueno"},    {range:"14.6–17.0", pts:"26–47", label:"Promedio"},  {range:"> 17.0",   pts:"10–25", label:"Por desarrollar"}],
          sub12:  [{range:"< 9.0",    pts:"90–99", label:"Maestro"},         {range:"9.0–11.0",  pts:"70–89", label:"Muy hábil"},  {range:"11.1–13.0", pts:"48–69", label:"Bueno"},    {range:"13.1–15.5", pts:"26–47", label:"Promedio"},  {range:"> 15.5",   pts:"10–25", label:"Por desarrollar"}],
          sub14:  [{range:"< 8.2",    pts:"90–99", label:"Maestro"},         {range:"8.2–9.8",   pts:"72–89", label:"Muy hábil"},  {range:"9.9–11.5",  pts:"50–71", label:"Bueno"},    {range:"11.6–13.5", pts:"28–49", label:"Promedio"},  {range:"> 13.5",   pts:"10–27", label:"Por desarrollar"}],
          sub16:  [{range:"< 7.8",    pts:"90–99", label:"Maestro"},         {range:"7.8–9.2",   pts:"72–89", label:"Muy hábil"},  {range:"9.3–10.8",  pts:"52–71", label:"Bueno"},    {range:"10.9–12.5", pts:"30–51", label:"Promedio"},  {range:"> 12.5",   pts:"10–29", label:"Por desarrollar"}],
          sub18:  [{range:"< 7.4",    pts:"90–99", label:"Maestro"},         {range:"7.4–8.8",   pts:"74–89", label:"Muy hábil"},  {range:"8.9–10.2",  pts:"52–73", label:"Bueno"},    {range:"10.3–12.0", pts:"30–51", label:"Promedio"},  {range:"> 12.0",   pts:"10–29", label:"Por desarrollar"}],
          sub21:  [{range:"< 7.2",    pts:"90–99", label:"Maestro"},         {range:"7.2–8.6",   pts:"74–89", label:"Muy hábil"},  {range:"8.7–10.0",  pts:"54–73", label:"Bueno"},    {range:"10.1–11.8", pts:"32–53", label:"Promedio"},  {range:"> 11.8",   pts:"10–31", label:"Por desarrollar"}],
          senior: [{range:"< 7.0",    pts:"92–99", label:"Maestro del regate"},{range:"7.0–8.5",  pts:"74–91", label:"Muy hábil"},  {range:"8.6–10.0",  pts:"54–73", label:"Bueno"},    {range:"10.1–12.0", pts:"32–53", label:"Promedio"},  {range:"> 12.0",   pts:"10–31", label:"Por desarrollar"}],
        },
      },
      {
        name: "Control y toque (jueguito)", objective: "Número máximo de toques consecutivos sin perder el balón",
        setup: "Espacio libre 3×3 m. Cualquier parte del cuerpo excepto brazos. El evaluador cuenta en voz alta.",
        execution: "2 intentos de 60 segundos. Si pierde el balón, se cuenta lo acumulado. Se toma el máximo.",
        attempts: 2, best: "Número máximo de toques en cualquier intento.",
        unit: "toques",
        scoring: {
          sub10:  [{range:"> 25",   pts:"90–99", label:"Técnico élite"}, {range:"16–25", pts:"70–89", label:"Muy técnico"}, {range:"8–15",  pts:"48–69", label:"Bueno"},   {range:"3–7",   pts:"26–47", label:"Básico"},   {range:"< 3",   pts:"10–25", label:"Iniciando"}],
          sub12:  [{range:"> 35",   pts:"90–99", label:"Técnico élite"}, {range:"25–35", pts:"70–89", label:"Muy técnico"}, {range:"14–24", pts:"48–69", label:"Bueno"},   {range:"6–13",  pts:"26–47", label:"Básico"},   {range:"< 6",   pts:"10–25", label:"Por mejorar"}],
          sub14:  [{range:"> 50",   pts:"90–99", label:"Técnico élite"}, {range:"36–50", pts:"70–89", label:"Muy técnico"}, {range:"22–35", pts:"50–69", label:"Bueno"},   {range:"10–21", pts:"28–49", label:"Básico"},   {range:"< 10",  pts:"10–27", label:"Por mejorar"}],
          sub16:  [{range:"> 65",   pts:"90–99", label:"Técnico élite"}, {range:"50–65", pts:"70–89", label:"Muy técnico"}, {range:"33–49", pts:"50–69", label:"Bueno"},   {range:"15–32", pts:"28–49", label:"Básico"},   {range:"< 15",  pts:"10–27", label:"Por mejorar"}],
          sub18:  [{range:"> 75",   pts:"90–99", label:"Técnico élite"}, {range:"58–75", pts:"72–89", label:"Muy técnico"}, {range:"38–57", pts:"52–71", label:"Bueno"},   {range:"18–37", pts:"30–51", label:"Básico"},   {range:"< 18",  pts:"10–29", label:"Por mejorar"}],
          sub21:  [{range:"> 80",   pts:"90–99", label:"Técnico élite"}, {range:"62–80", pts:"72–89", label:"Muy técnico"}, {range:"42–61", pts:"52–71", label:"Bueno"},   {range:"20–41", pts:"30–51", label:"Básico"},   {range:"< 20",  pts:"10–29", label:"Por mejorar"}],
          senior: [{range:"> 80",   pts:"90–99", label:"Técnico élite"}, {range:"60–80", pts:"72–89", label:"Muy técnico"}, {range:"40–59", pts:"52–71", label:"Bueno"},   {range:"20–39", pts:"30–51", label:"Básico"},   {range:"< 20",  pts:"10–29", label:"Por mejorar"}],
        },
      },
    ],
    formula: "DRI = (Slalom cronometrado × 0.55) + (Control y toque × 0.45)",
  },
  {
    key: "defending", label: "DEFENSA", abbr: "DEF", color: "#6c63ff", icon: "🛡️",
    description: "Evalúa el desplazamiento defensivo, posicionamiento y tiempo de reacción. Todos los tests los ejecuta el jugador solo, sin necesitar terceros.",
    equipment: [
      "5 conos de señalización", "4 conos de colores distintos (rojo, azul, amarillo, verde)",
      "Cronómetro", "Cinta métrica", "Tarjetas o banderines de color (opcional)",
    ],
    tests: [
      {
        name: "Slalom Defensivo Cronometrado", objective: "Medir desplazamiento lateral en postura defensiva baja y velocidad de reacción",
        setup: "5 conos en línea recta separados 1.5 m entre sí (total ~6 m). El jugador se coloca frente al primer cono en posición defensiva: rodillas semiflexionadas, espalda recta, centro de gravedad bajo.",
        execution: "El jugador se desplaza lateralmente (shuffle defensivo, sin cruzar los pies) tocando cada cono con la mano exterior. Al llegar al último cono regresa al inicio. PENALIZACIÓN: +0.5 seg si cruza los pies o pierde la postura defensiva.",
        attempts: 3, best: "Se toma el mejor tiempo válido de 3 intentos (1 min descanso entre ellos).",
        unit: "segundos",
        scoring: {
          sub10:  [{range:"< 5.0",  pts:"92–99", label:"Defensor élite"}, {range:"5.0–6.2",  pts:"74–91", label:"Muy ágil"},   {range:"6.3–7.5",  pts:"52–73", label:"Bueno"},    {range:"7.6–9.0",  pts:"30–51", label:"Promedio"}, {range:"> 9.0",  pts:"10–29", label:"Por mejorar"}],
          sub12:  [{range:"< 4.5",  pts:"92–99", label:"Defensor élite"}, {range:"4.5–5.5",  pts:"74–91", label:"Muy ágil"},   {range:"5.6–6.8",  pts:"52–73", label:"Bueno"},    {range:"6.9–8.2",  pts:"30–51", label:"Promedio"}, {range:"> 8.2",  pts:"10–29", label:"Por mejorar"}],
          sub14:  [{range:"< 4.1",  pts:"92–99", label:"Defensor élite"}, {range:"4.1–5.0",  pts:"74–91", label:"Muy ágil"},   {range:"5.1–6.1",  pts:"52–73", label:"Bueno"},    {range:"6.2–7.4",  pts:"30–51", label:"Promedio"}, {range:"> 7.4",  pts:"10–29", label:"Por mejorar"}],
          sub16:  [{range:"< 3.8",  pts:"92–99", label:"Defensor élite"}, {range:"3.8–4.6",  pts:"74–91", label:"Muy ágil"},   {range:"4.7–5.6",  pts:"52–73", label:"Bueno"},    {range:"5.7–6.8",  pts:"30–51", label:"Promedio"}, {range:"> 6.8",  pts:"10–29", label:"Por mejorar"}],
          sub18:  [{range:"< 3.6",  pts:"92–99", label:"Defensor élite"}, {range:"3.6–4.3",  pts:"74–91", label:"Muy ágil"},   {range:"4.4–5.3",  pts:"52–73", label:"Bueno"},    {range:"5.4–6.4",  pts:"30–51", label:"Promedio"}, {range:"> 6.4",  pts:"10–29", label:"Por mejorar"}],
          sub21:  [{range:"< 3.4",  pts:"92–99", label:"Defensor élite"}, {range:"3.4–4.1",  pts:"74–91", label:"Muy ágil"},   {range:"4.2–5.0",  pts:"52–73", label:"Bueno"},    {range:"5.1–6.1",  pts:"30–51", label:"Promedio"}, {range:"> 6.1",  pts:"10–29", label:"Por mejorar"}],
          senior: [{range:"< 3.3",  pts:"92–99", label:"Defensor élite"}, {range:"3.3–4.0",  pts:"74–91", label:"Muy ágil"},   {range:"4.1–4.9",  pts:"52–73", label:"Bueno"},    {range:"5.0–6.0",  pts:"30–51", label:"Promedio"}, {range:"> 6.0",  pts:"10–29", label:"Por mejorar"}],
        },
      },
      {
        name: "Reacción a Señal Visual (10 señales)", objective: "Medir tiempo de reacción, anticipación y cambio de dirección",
        setup: "4 conos de colores distintos en las esquinas de un cuadrado de 4×4 m. El jugador parte de pie en el centro. El evaluador señala aleatoriamente un cono desde fuera.",
        execution: "El jugador sprint hasta el cono indicado, lo toca con la mano y regresa al centro antes de la siguiente señal. 10 señales en total. PENALIZACIÓN: +1 seg por cada error de cono o salida anticipada.",
        attempts: 1, best: "Tiempo total de los 10 desplazamientos completos.",
        unit: "segundos (10 señales)",
        scoring: {
          sub10:  [{range:"< 22",   pts:"92–99", label:"Reacción élite"}, {range:"22–27",  pts:"74–91", label:"Muy reactivo"}, {range:"28–33",  pts:"52–73", label:"Bueno"},    {range:"34–40",  pts:"30–51", label:"Promedio"}, {range:"> 40",   pts:"10–29", label:"Por mejorar"}],
          sub12:  [{range:"< 20",   pts:"92–99", label:"Reacción élite"}, {range:"20–24",  pts:"74–91", label:"Muy reactivo"}, {range:"25–30",  pts:"52–73", label:"Bueno"},    {range:"31–37",  pts:"30–51", label:"Promedio"}, {range:"> 37",   pts:"10–29", label:"Por mejorar"}],
          sub14:  [{range:"< 18",   pts:"92–99", label:"Reacción élite"}, {range:"18–22",  pts:"74–91", label:"Muy reactivo"}, {range:"23–27",  pts:"52–73", label:"Bueno"},    {range:"28–34",  pts:"30–51", label:"Promedio"}, {range:"> 34",   pts:"10–29", label:"Por mejorar"}],
          sub16:  [{range:"< 16",   pts:"92–99", label:"Reacción élite"}, {range:"16–20",  pts:"74–91", label:"Muy reactivo"}, {range:"21–25",  pts:"52–73", label:"Bueno"},    {range:"26–31",  pts:"30–51", label:"Promedio"}, {range:"> 31",   pts:"10–29", label:"Por mejorar"}],
          sub18:  [{range:"< 15",   pts:"92–99", label:"Reacción élite"}, {range:"15–18",  pts:"74–91", label:"Muy reactivo"}, {range:"19–23",  pts:"52–73", label:"Bueno"},    {range:"24–29",  pts:"30–51", label:"Promedio"}, {range:"> 29",   pts:"10–29", label:"Por mejorar"}],
          sub21:  [{range:"< 14",   pts:"92–99", label:"Reacción élite"}, {range:"14–17",  pts:"74–91", label:"Muy reactivo"}, {range:"18–22",  pts:"52–73", label:"Bueno"},    {range:"23–28",  pts:"30–51", label:"Promedio"}, {range:"> 28",   pts:"10–29", label:"Por mejorar"}],
          senior: [{range:"< 14",   pts:"92–99", label:"Reacción élite"}, {range:"14–17",  pts:"74–91", label:"Muy reactivo"}, {range:"18–21",  pts:"52–73", label:"Bueno"},    {range:"22–27",  pts:"30–51", label:"Promedio"}, {range:"> 27",   pts:"10–29", label:"Por mejorar"}],
        },
      },
    ],
    formula: "DEF = (Slalom defensivo × 0.50) + (Reacción a señal visual × 0.50)",
  },
  {
    key: "physical", label: "FÍSICO", abbr: "PHY", color: "#ff6ec7", icon: "💪",
    description: "Evalúa la resistencia aeróbica, fuerza explosiva y capacidad de duelo físico del jugador.",
    equipment: [
      "Cinta métrica (20 m)", "Conos de delimitación",
      "Audio del Test Yo-Yo", "Silbato", "Pared o tablero de salto vertical",
    ],
    tests: [
      {
        name: "Test Yo-Yo Intermitente (Nivel 1)", objective: "Medir capacidad aeróbica y resistencia máxima",
        setup: "Dos líneas paralelas a 20 m con zona de descanso de 5 m. Audio del test dicta los tiempos con pitidos crecientes.",
        execution: "Correr entre líneas al ritmo del audio. 10 seg de descanso entre series. Test termina cuando no llega 2 veces consecutivas.",
        attempts: 1, best: "Se registra el último nivel y repetición completada.",
        unit: "nivel Yo-Yo",
        scoring: {
          sub10:  [{range:"Nivel ≥ 9",   pts:"88–99", label:"Resistencia élite"}, {range:"Nivel 7–8",   pts:"66–87", label:"Muy buena"},  {range:"Nivel 5–6",   pts:"44–65", label:"Buena"},    {range:"Nivel < 5",   pts:"10–43", label:"Por mejorar"}],
          sub12:  [{range:"Nivel ≥ 11",  pts:"88–99", label:"Resistencia élite"}, {range:"Nivel 9–10",  pts:"68–87", label:"Muy buena"},  {range:"Nivel 7–8",   pts:"46–67", label:"Buena"},    {range:"Nivel < 7",   pts:"10–45", label:"Por mejorar"}],
          sub14:  [{range:"Nivel ≥ 13",  pts:"88–99", label:"Resistencia élite"}, {range:"Nivel 11–12", pts:"68–87", label:"Muy buena"},  {range:"Nivel 9–10",  pts:"48–67", label:"Buena"},    {range:"Nivel 7–8",   pts:"28–47", label:"Regular"},  {range:"Nivel < 7",  pts:"10–27", label:"Por mejorar"}],
          sub16:  [{range:"Nivel ≥ 15",  pts:"88–99", label:"Resistencia élite"}, {range:"Nivel 13–14", pts:"70–87", label:"Muy buena"},  {range:"Nivel 11–12", pts:"50–69", label:"Buena"},    {range:"Nivel 9–10",  pts:"30–49", label:"Regular"},  {range:"Nivel < 9",  pts:"10–29", label:"Por mejorar"}],
          sub18:  [{range:"Nivel ≥ 17",  pts:"88–99", label:"Resistencia élite"}, {range:"Nivel 15–16", pts:"70–87", label:"Muy buena"},  {range:"Nivel 13–14", pts:"52–69", label:"Buena"},    {range:"Nivel 11–12", pts:"32–51", label:"Regular"},  {range:"Nivel < 11", pts:"10–31", label:"Por mejorar"}],
          sub21:  [{range:"Nivel ≥ 18",  pts:"88–99", label:"Resistencia élite"}, {range:"Nivel 16–17", pts:"72–87", label:"Muy buena"},  {range:"Nivel 14–15", pts:"52–71", label:"Buena"},    {range:"Nivel 12–13", pts:"32–51", label:"Regular"},  {range:"Nivel < 12", pts:"10–31", label:"Por mejorar"}],
          senior: [{range:"Nivel ≥ 19",  pts:"90–99", label:"Resistencia élite"}, {range:"Nivel 16–18", pts:"72–89", label:"Muy buena"},  {range:"Nivel 13–15", pts:"52–71", label:"Buena"},    {range:"Nivel 10–12", pts:"32–51", label:"Regular"},  {range:"Nivel < 10", pts:"10–31", label:"Por mejorar"}],
        },
      },
      {
        name: "Salto Vertical (CMJ)", objective: "Medir fuerza explosiva de piernas (contramovimiento)",
        setup: "Pared con cinta métrica. El jugador marca su alcance estático con brazo extendido como referencia.",
        execution: "Flexión libre de rodillas y salto máximo tocando la pared. 3 intentos con 60 seg descanso. Se mide la diferencia en cm.",
        attempts: 3, best: "Mejor salto de 3 intentos.",
        unit: "centímetros",
        scoring: {
          sub10:  [{range:"> 28",  pts:"90–99", label:"Potente"},       {range:"22–28", pts:"68–89", label:"Bueno"},        {range:"15–21", pts:"44–67", label:"Promedio"}, {range:"< 15",  pts:"10–43", label:"Por mejorar"}],
          sub12:  [{range:"> 34",  pts:"90–99", label:"Potente"},       {range:"27–34", pts:"68–89", label:"Bueno"},        {range:"19–26", pts:"44–67", label:"Promedio"}, {range:"< 19",  pts:"10–43", label:"Por mejorar"}],
          sub14:  [{range:"> 42",  pts:"90–99", label:"Muy potente"},   {range:"34–42", pts:"70–89", label:"Potente"},      {range:"25–33", pts:"48–69", label:"Bueno"},    {range:"< 25",  pts:"10–47", label:"Por mejorar"}],
          sub16:  [{range:"> 52",  pts:"90–99", label:"Muy potente"},   {range:"42–52", pts:"70–89", label:"Potente"},      {range:"31–41", pts:"48–69", label:"Bueno"},    {range:"< 31",  pts:"10–47", label:"Por mejorar"}],
          sub18:  [{range:"> 62",  pts:"90–99", label:"Muy potente"},   {range:"50–62", pts:"72–89", label:"Potente"},      {range:"38–49", pts:"50–71", label:"Bueno"},    {range:"< 38",  pts:"10–49", label:"Por mejorar"}],
          sub21:  [{range:"> 68",  pts:"90–99", label:"Élite"},         {range:"56–68", pts:"72–89", label:"Muy potente"},  {range:"44–55", pts:"52–71", label:"Bueno"},    {range:"< 44",  pts:"10–51", label:"Por mejorar"}],
          senior: [{range:"> 70",  pts:"90–99", label:"Potencia élite"},{range:"60–70", pts:"72–89", label:"Muy potente"},  {range:"48–59", pts:"52–71", label:"Bueno"},    {range:"< 48",  pts:"10–51", label:"Por mejorar"}],
        },
      },
    ],
    formula: "PHY = (Test Yo-Yo × 0.55) + (Salto vertical CMJ × 0.30) + (Complexión observada × 0.15)",
  },
];
